{ config, lib, pkgs, tailnetFqdn, apertureUrl, ... }:
let
  # Every service that declared a public face, in `public.order`
  # (hosts/rpi5/lib/service-registration.nix). Was services-registry.nix.
  #
  # A service with no `tile` is routed but renders nothing — the front proxy, the
  # MCP gateway, the notify aggregator, the Epic captcha portal, and homepage
  # itself. That used to be spelled as `category = "Infrastructure"` and enforced
  # three times over (a name test for "Homepage", a category test, and omission
  # from categoryOrder below), none of which said "hidden".
  visibleEntries = builtins.filter (e: e.tile != null) config.nic.publicEntries;

  # Ordered category list (controls display order on the dashboard).
  # Tile order within each category comes from `public.order`.
  categoryOrder = [
    "Apps"
    "Backend"
  ];

  # Two sources of tiles, flattened to one shape before anything sorts or groups
  # them, so the rest of this file never asks which kind it is holding.
  #
  # publicUrl already folds in the port rule (omitted on 443, the bare-URL funnel)
  # and the path-mux prefix. deepLink is the cosmetic tail — only Home Assistant
  # sets one, to land on its "Mine" dashboard.
  serviceTiles = map (e: e.tile // {
    inherit (e) order;
    href = e.publicUrl + lib.optionalString (e.tile.deepLink != null) e.tile.deepLink;
  }) visibleEntries;

  # Things this host neither runs nor routes — Aperture only, see
  # `nic.externalTiles` in lib/service-registration.nix. href is given outright.
  externalTiles = map (e: e.tile // { inherit (e) order href; }) config.nic.externalTiles;

  # One number line for both lists. Ties break on name so the order is stable
  # across evals even though the uniqueness assertion covers services only.
  allTiles = lib.sort
    (a: b: if a.order != b.order then a.order < b.order else a.name < b.name)
    (serviceTiles ++ externalTiles);

  # Build tile config, including widget if the entry has one.
  #
  # No tile sets `siteMonitor`. Homepage pings it every ~5 min from the browser,
  # which (a) reported the Backend tiles as down — tiny-llm-gate and Cyrus answer
  # 404 on `/` and Hydroxide answers 401, none of which means "unhealthy" — and
  # (b) kept every socket-activated backend pinned in memory on a 3.9 GB box.
  # Liveness is Beszel's job; the tiles are links plus a daily stat.
  mkTile = t:
    { inherit (t) icon href description; }
    // lib.optionalAttrs (t.widget != null) { inherit (t) widget; };

  # Build the services list: one attrset per category, each containing service tiles
  servicesByCategory = builtins.filter (group: group != null) (
    map (cat:
      let entries = builtins.filter (t: t.category == cat) allTiles;
      in if entries == [] then null
      else {
        "${cat}" = map (t: { "${t.name}" = mkTile t; }) entries;
      }
    ) categoryOrder
  );

in
{
  # Bind to localhost only — Tailscale Serve proxies from the tailnet interface
  # and would conflict on 0.0.0.0:8082.
  # Allow statfs on /home so the resources widget can report disk usage
  systemd.services.homepage-dashboard.serviceConfig.ProtectHome = lib.mkForce "read-only";
  systemd.services.homepage-dashboard.environment.HOSTNAME = "127.0.0.1";
  # Cap V8 heap — Next.js idles at ~61 MB; 128 MB gives headroom for widget rendering
  systemd.services.homepage-dashboard.environment.NODE_OPTIONS = "--max-old-space-size=128";

  # Widget API keys, from the env file generated by the setup oneshot below. No
  # tile references {{HOMEPAGE_VAR_*}} any more — every widget reads the
  # homepage-stats aggregator instead — so these are really for homepage-stats,
  # which reads the same file. Kept on the dashboard unit as the ordering anchor.
  systemd.services.homepage-dashboard.serviceConfig.EnvironmentFile = lib.mkForce "/run/homepage-dashboard/env";
  systemd.services.homepage-dashboard.after = [ "homepage-dashboard-env.service" ];
  systemd.services.homepage-dashboard.requires = [ "homepage-dashboard-env.service" ];

  # Oneshot: generate env file with secrets before homepage starts
  systemd.services.homepage-dashboard-env = {
    description = "Generate homepage-dashboard environment file with secrets";
    wantedBy = [ "multi-user.target" ];
    before = [ "homepage-dashboard.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      mkdir -p /run/homepage-dashboard
      cat > /run/homepage-dashboard/env <<ENVEOF
      HOMEPAGE_VAR_IMMICH_KEY=$(cat ${config.age.secrets.immich-api-key.path})
      # No AFFINE_TOKEN: AFFiNE 0.27.3 dropped user access tokens from its API, so
      # the one in affine-token.age is dead and cannot be re-minted. The affine
      # fetcher reads AFFiNE's Postgres directly instead — see fetch_affine.
      HOMEPAGE_VAR_SURE_KEY=$(grep SURE_API_KEY ${config.age.secrets.agent-env.path} | cut -d= -f2)
      HOMEPAGE_VAR_HA_TOKEN=$(grep HA_TOKEN ${config.age.secrets.agent-env.path} | cut -d= -f2)
      HOMEPAGE_VAR_NEXTCLOUD_PASSWORD=$(tr -d '\r\n' < ${config.age.secrets.nextcloud-homepage-password.path})
      # Wealthfolio has no API key, only a session cookie behind a password —
      # the same one the Sure mirror logs in with, so it is read from that
      # secret rather than stored a second time. The single quotes are stripped
      # here because this file is parsed by the fetcher, not by systemd.
      HOMEPAGE_VAR_WEALTHFOLIO_PASSWORD=$(grep WF_PASSWORD ${config.age.secrets.wealthfolio-sync-env.path} | cut -d= -f2- | tr -d "'\"")
      ENVEOF
    '';
  };

  # The upstream module writes services.yaml via environment.etc, which does NOT
  # restart the service — so homepage kept serving the PREVIOUS tile config
  # while the stats API already served the new field names, and every renamed
  # field rendered as "NaN" until something happened to restart it. Nothing
  # rebuilds a widget's mappings more often than a dashboard, so tie the two
  # together explicitly.
  systemd.services.homepage-dashboard.restartTriggers = [
    config.environment.etc."homepage-dashboard/services.yaml".source
  ];

  # Tiny stats aggregation API for homepage widgets that need data from multiple endpoints
  systemd.services.homepage-stats = {
    description = "Homepage stats aggregation (JSON on :8087)";
    wantedBy = [ "multi-user.target" ];
    # Ordered after wealthfolio because a rebuild restarts both, and its fetcher
    # logs in over HTTP — losing that race writes a connection-refused error
    # into the daily cache. Ordering is not a guarantee (systemd starts, it does
    # not wait for the port), which is why an errored key is now retried rather
    # than frozen; this just makes the race rare instead of routine.
    after = [ "homepage-dashboard-env.service" "wealthfolio.service" ];
    serviceConfig = {
      Type = "simple";
      Restart = "on-failure";
      RestartSec = "10s";
      # systemd auto-creates /var/lib/homepage-stats and exports
      # STATE_DIRECTORY for the cache file.
      StateDirectory = "homepage-stats";
      ExecStart = "${pkgs.nicos-scripts}/bin/homepage-stats";
      Environment = [
        "CURL_BIN=${pkgs.curl}/bin/curl"
        "SQLITE_BIN=${pkgs.sqlite}/bin/sqlite3"
        "PSQL_BIN=${pkgs.postgresql}/bin/psql"
        "RUNUSER_BIN=${pkgs.util-linux}/bin/runuser"
        # The Aperture tile's source. Passed in rather than defaulted in Python so
        # the flake's `apertureUrl` stays the single place the tailnet name is
        # spelled — fetch_aperture's default is only there for the tests.
        "APERTURE_METRICS_URL=${apertureUrl}/metrics"
      ];
    };
  };

  services.homepage-dashboard = {
    enable = true;
    listenPort = 8082;
    allowedHosts = lib.concatStringsSep "," [
      "localhost:8082"
      "127.0.0.1:8082"
      "${tailnetFqdn}:8082"
    ];

    settings = {
      title = "nic-os";
      favicon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/nixos.svg";
      headerStyle = "clean";
      # List format preserves display order (Nix attrsets sort alphabetically)
      # `columns` is load-bearing for how the tile ORDER reads, not just for
      # density: Apps is grouped in fours to match `columns = 4` so each row is one
      # subject (see the `order` option in lib/service-registration.nix). Changing
      # 4 here silently un-groups every row.
      #
      # Quick Links is 5 across because it holds 5 bookmarks. It was 6 at 3 columns
      # — two clean rows — until Aperture graduated to a real tile and left 5,
      # which at 3 columns is a row of three and an orphaned pair.
      layout = [
        { "Quick Links" = { style = "row"; columns = 5; header = false; }; }
        { "Apps"        = { style = "row"; columns = 4; }; }
        { "Backend"     = { style = "row"; columns = 4; }; }
      ];
    };

    bookmarks = [
      {
        "Quick Links" = [
          { "GitHub Notifications" = [{ icon = "github.svg"; href = "https://github.com/notifications"; }]; }
          { "Tailscale Admin" = [{ icon = "tailscale.svg"; href = "https://login.tailscale.com/admin/machines"; }]; }
          { "nic-os PRs" = [{ icon = "github.svg"; href = "https://github.com/nSimonFR/nic-os/pulls"; }]; }
          # Aperture was here. It is a real tile now (aperture-sync.nix, via
          # nic.externalTiles) because a bookmark cannot carry a widget, and the
          # most expensive thing on the box should show its token rate.
          { "IT Tools" = [{ icon = "si-hackthebox"; href = "https://it-tools.tech/"; }]; }
          { "BentoPDF" = [{ icon = "mdi-file-pdf-box"; href = "https://bentopdf.com/"; }]; }
        ];
      }
    ];

    services = servicesByCategory;

    widgets = [
      {
        resources = {
          cpu = true;
          memory = true;
          disk = [ "/" "/home" "/mnt/data" ];
          expanded = true;
        };
      }
      {
        # Paris weather — no API key needed
        openmeteo = {
          label = "Paris";
          latitude = 48.8566;
          longitude = 2.3522;
          units = "metric";
          cache = 15;
        };
      }
      {
        search = {
          provider = "google";
          target = "_blank";
        };
      }
    ];
  };

  # ── Service registration (hosts/rpi5/lib/service-registration.nix) ──────────────
  nic.services.homepage = {
    backup        = [ "none" ];
    backupNote    = "dashboard config is generated from nic.services.*.public; the stats aggregator only caches";
    heavyUnits    = [ "homepage-dashboard.service" "homepage-stats.service" ];
    heavyPriority = 160;

    # No tile: the dashboard does not link to itself.
    public = {
      order   = 360;
      port    = 8082;
      backend = "http://127.0.0.1:8082";
    };
  };
}
