{ config, lib, pkgs, tailnetFqdn, voiceWebhookPort, ... }:
let
  registry = import ./services-registry.nix { inherit voiceWebhookPort; };
  allEntries = registry.serveEntries ++ registry.funnelEntries;

  # Hide Homepage and Infrastructure from the dashboard
  visibleEntries = builtins.filter (e: e.name != "Homepage" && e.category != "Infrastructure") allEntries;

  # Explicit tile ordering per category (entries not listed here appear at the end)
  tileOrder = {
    "Apps" = [ "AFFiNE" "Immich" "Sure" "Open WebUI" ];
    "Services" = [ "Vaultwarden" "Home Assistant" "Filebrowser" "Forgejo" ];
  };

  sortEntries = cat: entries:
    let
      order = tileOrder.${cat} or [];
      indexOf = name: let idx = lib.lists.findFirstIndex (n: n == name) (builtins.length order) order; in idx;
    in builtins.sort (a: b: indexOf a.name < indexOf b.name) entries;

  # Ordered category list (controls display order on the dashboard)
  categoryOrder = [
    "Apps"
    "Services"
    "Monitoring"
    "Backend"
  ];

  entriesForCategory = cat:
    builtins.filter (e: e.category == cat) visibleEntries;

  # Build tile config, including widget if the entry has one
  mkTile = e:
    let
      base = {
        icon = e.icon;
        href = "https://${tailnetFqdn}:${toString e.port}";
        inherit (e) description;
        siteMonitor = "https://${tailnetFqdn}:${toString e.port}";
      };
      widgetAttr = if e ? widget then { inherit (e) widget; } else {};
    in base // widgetAttr;

  # Build the services list: one attrset per category, each containing service tiles
  servicesByCategory = builtins.filter (group: group != null) (
    map (cat:
      let entries = sortEntries cat (entriesForCategory cat);
      in if entries == [] then null
      else {
        "${cat}" = map (e: {
          "${e.name}" = mkTile e;
        }) entries;
      }
    ) categoryOrder
  );

in
{
  # Bind to localhost only — Tailscale Serve proxies from the tailnet interface
  # and would conflict on 0.0.0.0:8082.
  systemd.services.homepage-dashboard.environment.HOSTNAME = "127.0.0.1";

  # Load widget API keys from env file generated by the setup oneshot
  systemd.services.homepage-dashboard.serviceConfig.EnvironmentFile = lib.mkForce "/run/homepage-dashboard/env";
  systemd.services.homepage-dashboard.after = [ "homepage-dashboard-env.service" ];
  systemd.services.homepage-dashboard.requires = [ "homepage-dashboard-env.service" ];

  # Oneshot: generate env file with secrets before homepage starts
  systemd.services.homepage-dashboard-env = {
    description = "Generate homepage-dashboard environment file with secrets";
    wantedBy = [ "multi-user.target" ];
    before = [ "homepage-dashboard.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      mkdir -p /run/homepage-dashboard
      cat > /run/homepage-dashboard/env <<ENVEOF
      HOMEPAGE_VAR_IMMICH_KEY=$(cat ${config.age.secrets.immich-api-key.path})
      HOMEPAGE_VAR_BESZEL_PASS=homepage-widget-pass
      HOMEPAGE_VAR_AFFINE_TOKEN=$(cat ${config.age.secrets.affine-token.path})
      HOMEPAGE_VAR_SURE_KEY=$(grep SURE_API_KEY ${config.age.secrets.openclaw-env.path} | cut -d= -f2)
      ENVEOF
    '';
  };

  # Tiny stats aggregation API for homepage widgets that need data from multiple endpoints
  systemd.services.homepage-stats = {
    description = "Homepage stats aggregation (JSON on :8087)";
    wantedBy = [ "multi-user.target" ];
    after = [ "homepage-dashboard-env.service" ];
    serviceConfig = {
      Type = "simple";
      Restart = "on-failure";
      RestartSec = "10s";
      ExecStart = "${pkgs.python3}/bin/python3 ${./homepage-stats.py}";
      Environment = [
        "CURL_BIN=${pkgs.curl}/bin/curl"
        "SQLITE_BIN=${pkgs.sqlite}/bin/sqlite3"
      ];
    };
  };

  services.homepage-dashboard = {
    enable = true;
    listenPort = 8082;
    allowedHosts = lib.concatStringsSep "," [
      "localhost:8082"
      "127.0.0.1:8082"
      "${tailnetFqdn}:8082"
    ];

    settings = {
      title = "nic-os";
      favicon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/nixos.svg";
      headerStyle = "clean";
      # List format preserves display order (Nix attrsets sort alphabetically)
      layout = [
        { "Quick Links" = { style = "row"; columns = 3; header = false; }; }
        { "Apps"        = { style = "row"; columns = 4; }; }
        { "Monitoring"  = { style = "row"; columns = 4; }; }
        { "Services"    = { style = "row"; columns = 4; }; }
        { "Backend"     = { style = "row"; columns = 4; }; }
      ];
    };

    bookmarks = [
      {
        "Quick Links" = [
          { "YouTube" = [{ icon = "youtube.svg"; href = "https://www.youtube.com/"; }]; }
          { "GitHub Notifications" = [{ icon = "github.svg"; href = "https://github.com/notifications"; }]; }
          { "Tailscale Admin" = [{ icon = "tailscale.svg"; href = "https://login.tailscale.com/admin/machines"; }]; }
          { "nic-os PRs" = [{ icon = "github.svg"; href = "https://github.com/nSimonFR/nic-os/pulls"; }]; }
          { "IT Tools" = [{ icon = "si-hackthebox"; href = "https://it-tools.tech/"; }]; }
        ];
      }
    ];

    services = servicesByCategory;

    widgets = [
      {
        resources = {
          cpu = true;
          memory = true;
          disk = "/";
        };
      }
      {
        # Paris weather — no API key needed
        openmeteo = {
          label = "Paris";
          latitude = 48.8566;
          longitude = 2.3522;
          units = "metric";
          cache = 15;
        };
      }
      {
        search = {
          provider = "google";
          target = "_blank";
        };
      }
    ];
  };
}
