set -g default-terminal "xterm-256color"
set-option -g default-shell /bin/zsh

bind j select-pane -t :.+
bind k select-pane -t :.-

bind-key C-j resize-pane -D
bind-key C-k resize-pane -U
bind-key C-h resize-pane -L
bind-key C-l resize-pane -R

# Pane borders
set -g pane-border-lines heavy
set -g pane-border-style fg=colour240
set -g pane-active-border-style fg=colour39
