name: Commitlint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
